import { NextResponse } from "next/server"

const sampleTexts = [
  "The quick brown fox jumps over the lazy dog near the riverbank where children often play during summer afternoons, while their parents sit on wooden benches reading newspapers and watching the gentle flow of water that reflects the golden sunlight streaming through the canopy of ancient oak trees that have stood there for generations, providing shade and shelter to countless families who have made this peaceful spot their favorite weekend destination.",
  "Technology has revolutionized the way we communicate, work, and live our daily lives in the modern digital age, transforming everything from how we shop for groceries and connect with friends across the globe to how we learn new skills through online platforms and manage our finances with sophisticated mobile applications that were unimaginable just a few decades ago when people relied on traditional methods of correspondence and face-to-face interactions for most of their daily activities.",
  "Programming requires patience, practice, and persistence to master the art of writing clean and efficient code that solves complex problems while maintaining readability and scalability for future developers who might need to modify or extend the functionality, which is why experienced programmers emphasize the importance of following established conventions, writing comprehensive documentation, and continuously learning new technologies and methodologies that emerge in this rapidly evolving field.",
  "The ancient library contained thousands of books filled with wisdom from scholars across different civilizations, including rare manuscripts written on parchment by medieval monks who dedicated their lives to preserving knowledge, philosophical treatises from Greek and Roman thinkers who laid the foundation for Western thought, and scientific discoveries documented by brilliant minds who challenged conventional understanding and pushed the boundaries of human knowledge through careful observation and experimentation.",
  "Mountain climbing demands physical strength, mental fortitude, and careful preparation for unexpected weather conditions that can change rapidly at high altitudes, requiring climbers to carry specialized equipment including ropes, harnesses, helmets, and emergency supplies while maintaining constant awareness of their surroundings and the potential dangers posed by loose rocks, sudden storms, and the effects of reduced oxygen levels that can impair judgment and physical performance during challenging ascents.",
  "Cooking is both an art and a science that combines creativity with precise measurements and timing to create delicious meals that nourish the body and bring people together around the dinner table, where families and friends share stories, celebrate special occasions, and create lasting memories while enjoying carefully prepared dishes that reflect cultural traditions passed down through generations and adapted to modern tastes and dietary preferences.",
  "Education opens doors to new opportunities and helps individuals develop critical thinking skills throughout their lives, empowering them to make informed decisions, solve problems creatively, and contribute positively to society in various fields such as science, technology, arts, and humanities.",
  "Music has the power to evoke emotions, bring people together, and transcend cultural and language barriers, uniting diverse communities through shared melodies and rhythms that resonate deep within the human soul.",
  "Innovation drives progress in every field, from medicine and engineering to arts and environmental conservation, propelling humanity forward by fostering creativity, encouraging experimentation, and promoting the development of new technologies and solutions that address pressing challenges and improve the quality of life for all.",
]

export async function GET() {
  const randomText = sampleTexts[Math.floor(Math.random() * sampleTexts.length)]
  return NextResponse.json({ text: randomText })
}
